spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceapp
    password: root
    username: manager
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  
server:
  port: 8081  
