spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
        
  datasource:
    username: root
    password: manager
    url: jdbc:mysql://localhost:3306/ecommerceapp 

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
